library(argparse)

# argparse
parser <- ArgumentParser(description="Classify regions based on likelihoods generated by each model.")


# specify options
parser$add_argument("Input",type="character", help="Input file (the output file of the classification program),[required]")
#regionid, model I, model B, model N, model M
parser$add_argument("-c","--split_name", action="store_true", help="If true, region names will be split based on the second underscore.")
parser$add_argument("-n", "--model_name", type="character", default=c("MI", "MB", "MN", "MM"),help="Names of models")
parser$add_argument("-s", "--species", type="character", nargs="+", default=c("human","rhesus"), help="Species names.")
parser$add_argument("-sp1","--species_1",type="character", help="Peakregion file for species 1.")
parser$add_argument("-sp2","--species_2",type="character", help="Peakregion file for species 2")
parser$add_argument("-o","--output",default="classification_result",help="Output folder name. ")


normdiff <- function(x){
	return( (max(x) - min(x))/abs(max(x) + min(x)) )
}

rgroup <- function(x){
	return( model_name[which.max(x)] )
}

normbase <- function(x){
	return( max(x) + min(x) )
}


# get the input
args <- parser$parse_args()
print(args$Input)
model_name <<- args$model_name
fin <- read.table(args$Input, header=FALSE, sep="\t", stringsAsFactors = F)
model_count <- ncol(fin)-1
colnames(fin) <- c("seq_name", args$model_name)

if(args$split_name){
	print(fin$seq_name[1])
	Split <- strsplit(fin$seq_name, "_")
	peak_name <- sapply(Split, tail, 1)
}else{
	peak_name <- fin$seq_name
}

fin$peak_name <- peak_name
fin$group <- apply(fin[,2:(model_count+1)], 1, rgroup)
fin$diff <- apply(fin[,2:(model_count+1)], 1, normdiff)

nbase <- apply(fin[,2:(model_count+1)], 1, normbase)
#fin2 <-  fin
#fin2$cons_diff <- (fin2$MAP - fin2$MB)/abs(fin2$MAP + fin2$MB) 
#fin2$ind_diff <-  (fin2$MBP - fin2$MA)/abs(fin2$MBP + fin2$MA) 
#fin2[,2:(model_count+1)] <- ( fin2[,2:(model_count+1)] - apply(fin2[,2:(model_count+1)],1,mean) )/nbase
#fin2 <- fin2[order(-fin2$diff),]

fsp1 <- read.table(args$species_1, header=FALSE, sep="\t", stringsAsFactors = F)
fsp1 <- fsp1[,c(1:4)]
fsp2 <- read.table(args$species_2, header=FALSE, sep="\t", stringsAsFactors = F)
fsp2 <- fsp2[,c(1:4)]

colnames(fsp1)[1:3] <- apply(expand.grid(args$species[1],c("chr","start","end")),1,paste,collapse="_")
colnames(fsp1)[4] <- "peak_name"
colnames(fsp2)[1:3] <- apply(expand.grid(args$species[2],c("chr","start","end")),1,paste,collapse="_")
colnames(fsp2)[4] <- "peak_name"

dir.create(args$output)
setwd(args$output)
write.table(fin, file="region_info.txt", sep="\t",quote=F,col.names=T,row.names=F)
#write.table(fin2, file="region_normalized.txt", sep="\t",quote=F,col.names=T,row.names=F)


Merge1 <- merge(fin, fsp1, by="peak_name")
Merge2 <- merge(Merge1, fsp2, by="peak_name")
if("MI" %in% model_name){
	TypeA <- Merge2[which(Merge2$group=="MI"),]
	if(nrow(TypeA)>0){
		TypeA <- subset(TypeA[order(-TypeA$diff),], select=-c(seq_name))
		write.table(TypeA, file="TypeI.txt",sep="\t", quote=F, col.names=T,row.names=F)
	}
}
if("MB" %in% model_name){
	TypeB <- Merge2[which(Merge2$group=="MB"),]
	if(nrow(TypeB)>0){
		TypeB <- subset(TypeB[order(-TypeB$diff),], select=-c(seq_name))
		write.table(TypeB, file="TypeB.txt",sep="\t", quote=F, col.names=T,row.names=F)
	}
}
if("MN" %in% model_name){
	TypeAP <- Merge2[which(Merge2$group=="MN"),]
	if(nrow(TypeAP)>0){
		TypeAP <- subset(TypeAP[order(-TypeAP$diff),], select=-c(seq_name))
		write.table(TypeAP, file="TypeN.txt",sep="\t", quote=F, col.names=T,row.names=F)
	}
}
if("MM" %in% model_name){
	TypeBP <- Merge2[which(Merge2$group=="MM"),]
	if(nrow(TypeBP)>0){
		TypeBP <- subset(TypeBP[order(-TypeBP$diff),], select=-c(seq_name))
		write.table(TypeBP, file="TypeM.txt",sep="\t", quote=F, col.names=T,row.names=F)
	}
}






